services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
    environment:
      DEBUG: "true"
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
      SECRET_KEY: "79e297b2ca9872a6f6170e9b95f29e30"
    tty: true
    command: python -m src.app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
    ports:
      - "5432:5432"
